locale: en-US
encoding: UTF-8
url: https://mirrors.slickstack.io
repository: littlebizzy/slickstack
title: SlickStack Mirrors
description: Lightning-fast WordPress on Nginx
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
